In [1]:
import numpy as np

### set seed
A seed in NumPy (and other random libraries) is a starting value for the random number generator. Setting a seed (e.g., np.random.seed(123)) ensures that you get the same sequence of random numbers every time you run your code, making your results reproducible.

In [18]:
np.random.seed(123)

i = np.random.rand(5)
print(i)

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]


### set random state which is independent from the global seed

In [17]:
rs = np.random.RandomState(321)
rs.rand(10)

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ])

### generate a random sample from interval [0, 1) in a given shape

In [23]:
# generate a random scalar
print(np.random.rand())      

0.3921175181941505


In [5]:
# generate a 1-D array
print(np.random.rand(3))           

[0.9807642  0.68482974 0.4809319 ]


In [6]:
# generate a 2-D array
print(np.random.rand(3,3))          

[[0.39211752 0.34317802 0.72904971]
 [0.43857224 0.0596779  0.39804426]
 [0.73799541 0.18249173 0.17545176]]


### generate a sample from the standard normal distribution (mean = 0, var = 1)

In [7]:
print(np.random.randn(3,3))

[[ 2.20593008  2.18678609  1.0040539 ]
 [ 0.3861864   0.73736858  1.49073203]
 [-0.93583387  1.17582904 -1.25388067]]


### generate an array of random integers in a given interval [low, high)

In [8]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 5, 'i8'))

# generate a 2-D array with specific size
size = (2, 3)
print(np.random.randint(1, 10, size, 'i8'))

[2 9 4 6 1]
[[3 7 3]
 [5 5 7]]


### generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [9]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.46426806 0.56843069 0.30254945 0.49730879 0.68326291 0.91669867
 0.10892895 0.49549179 0.23283593 0.43686066]
[0.75154299 0.48089213 0.79772841 0.28270293 0.43341824 0.00975735
 0.34079598 0.68927201 0.86936929 0.26780382]
[0.45674792 0.26828131 0.8370528  0.27051466 0.53006201 0.17537266
 0.31496645 0.8911091  0.18033628 0.4943162 ]
[0.2122981  0.52087687 0.16009994 0.9190568  0.99428992 0.47704756
 0.30988351 0.50720432 0.2807932  0.76383669]


### generate a random sample from a given 1-D array

In [10]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
# The probabilities must sum to 1.0
# replace : boolean, optional Whether the sample is with or without replacement. Default is True, meaning that a value of a can be selected multiple times.
# p : 1-D array-like, optional.  The probabilities associated with each entry in a. If not given, the sample assumes a uniform distribution over all entries in a.

probs = np.array([0.1, 0.8, 0.1, 0.7, 0.6])
probs = probs / probs.sum()
print(np.random.choice(range(5), 10, replace=True, p=probs))

[1 3 4 1 1 4 3 2 1 1]


In [11]:
print(np.random.choice(100, 10))

[51  7 88 70 13 28 63 84 36 96]


In [12]:
print(np.random.choice([1,2,3], 10))

[2 1 1 1 3 3 2 2 1 3]


### shuffle an array in place

In [13]:
arr = np.array(range(12))
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [14]:
np.random.shuffle(arr)
print(arr)

[ 0  3  9 10  5  4  2  7  8 11  1  6]


### generate a permutation of an array

In [15]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [2 0 6 8 9 3 4 5 7 1]
