In [1]:
import numpy as np

In [2]:
arr = np.array(range(100)).reshape((10,10))
arr_1d = np.array(range(20))

### select an element by row and column indices

In [ ]:
print(arr[5][5])

# or more concisely
print(arr[5,5])

# Accessing a 1D array
print(arr_1d[7])

# Slicing a 1D array
print(arr_1d[5:10])  # From index 5 to 9
print(arr_1d[:5])    # From start to index 4 
print(arr_1d[5:])    # From index 5 to the end
print(arr_1d[::2])   # Every second element 

# Slicing a 2D array
print(arr[2:5, 3:6])  # Rows 2 to 4 and columns 3 to 5
print(arr[2:5, :])    # Rows 2 to 4 and all columns
print(arr[:, 3:6])    # All rows and columns 3 to 5     
print(arr[2:5, 3])    # Rows 2 to 4 and column 3
print(arr[2:5, 3:6])  # Rows 2 to 4 and columns 3 to 5      
print(arr[2:5, 3:6].shape)  # Shape of the sliced array
print(arr[2:5, 3:6].dtype)  # Data type of the sliced array

# Accessing a specific element in a 2D array
print(arr[2, 3])  # Element at row 2, column 3      

# Slicing a 2D array with a step
print(arr[::2, ::2])  # Every second row and every second column    

# Accessing a specific row or column
print(arr[5, :])    # Row 5   
print(arr[:, 5])    # Column 5

# Accessing a specific row or column with a step
print(arr[::2, 5])  # Every second row in column 5  

# Accessing a specific row or column with a step
print(arr[5, ::2])  # Row 5 and every second column

55
55
7
[5 6 7 8 9]
[0 1 2 3 4]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18]
[[23 24 25]
 [33 34 35]
 [43 44 45]]
[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[ 3  4  5]
 [13 14 15]
 [23 24 25]
 [33 34 35]
 [43 44 45]
 [53 54 55]
 [63 64 65]
 [73 74 75]
 [83 84 85]
 [93 94 95]]
[23 33 43]
[[23 24 25]
 [33 34 35]
 [43 44 45]]
(3, 3)
int64
23
[[ 0  2  4  6  8]
 [20 22 24 26 28]
 [40 42 44 46 48]
 [60 62 64 66 68]
 [80 82 84 86 88]]
[50 51 52 53 54 55 56 57 58 59]
[ 5 15 25 35 45 55 65 75 85 95]
[ 5 25 45 65 85]
[50 52 54 56 58]


### indexing with slicing

In [4]:
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


In [5]:
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(2,2,2,2)

# equivalent to arr[0,:,:,:]
print(arr[0, ...])    

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### assign a scalar to a slice by broadcasting

In [18]:
arr[1:3,:] = 100    # or simply arr[1:3]
arr[:,8:] = 100
print(arr)

[[  0   1   2   3]
 [100 100 100 100]
 [100 100 100 100]
 [ 12  13  14  15]]


### boolean indexing

In [7]:
arr1 = np.arange(25).reshape((5,5))

bools = np.array([True, True, False, True, False])
print(arr1[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [8]:
# negate the condition
print(arr1[~bools])    

[[10 11 12 13 14]
 [20 21 22 23 24]]


In [9]:
arr2 = np.array([1,2,3,4,5])
# multiple conditions
print(arr1[(arr2<2) | (arr2>4)])    

[[ 0  1  2  3  4]
 [20 21 22 23 24]]


### fancy indexing

In [10]:
arr = np.random.rand(10,10)

In [11]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])       

[0.43445724 0.31968979 0.37300584]


In [12]:
# select rows 3,1,2 and columns 6,4,8 
print(arr[[3,1,2]][:, [6,4,8]])    

[[0.95034591 0.65675324 0.75217175]
 [0.64690914 0.92501208 0.92326301]
 [0.09284265 0.08509389 0.48323886]]


### dimension inference

In [13]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(16)).reshape((4,-1))
print(arr.shape)

(4, 4)


### find elements/indices by conditions

In [14]:
arr = np.arange(16).reshape(4,4)

In [15]:
# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [16]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr>5, -1, 10))

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [17]:
# find the indices of the elements on conditions
print(np.argwhere(arr>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]
