In [1]:
import numpy as np

In [12]:
size = (3,3)
arr = np.random.randint(1, 9, size,'i8')

### sort an array along a specified axis

In [13]:
print(arr)
# sort along the row and return a copy
print('Sort along the row')
print(np.sort(arr, axis=0))   

# sort along the column and return a copy
print('Sort along the Columns : ')
print(np.sort(arr, axis=1)) 

# sort along the row and return the indices of the sorted elements
print('Sort along rows and return the indices : ')
print(np.argsort(arr, axis=0))  

# sort along the column and return the indices of the sorted elements
print('Sort along the column and return indices : ')
print(np.argsort(arr, axis=1))  

[[8 4 4]
 [1 2 4]
 [3 4 7]]
Sort along the row
[[1 2 4]
 [3 4 4]
 [8 4 7]]
Sort along the Columns : 
[[4 4 8]
 [1 2 4]
 [3 4 7]]
Sort along rows and return the indices : 
[[1 1 0]
 [2 0 1]
 [0 2 2]]
Sort along the column and return indices : 
[[1 2 0]
 [0 1 2]
 [0 1 2]]


In [4]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[2 2 2]
 [4 4 6]
 [6 7 7]]


In [5]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))    

[[2 2 2]
 [4 4 6]
 [6 7 7]]


In [6]:
# sort along the column in place
arr.sort(axis=1)    
print(arr)

[[2 2 2]
 [4 4 6]
 [6 7 7]]


### compute the indices that would sort an array along a specified axis

In [7]:
arr = np.random.rand(5,5)

In [8]:
# along the row
print(np.argsort(arr, axis=0))

[[4 4 1 2 2]
 [0 1 0 4 0]
 [2 3 4 1 1]
 [1 2 2 3 4]
 [3 0 3 0 3]]


In [9]:
# along the column
print(np.argsort(arr, axis=1))

[[0 4 3 2 1]
 [3 1 2 0 4]
 [4 3 1 0 2]
 [1 3 0 4 2]
 [1 3 0 2 4]]


In [10]:
# if axis=None, return the indices of a flattened array
print(np.argsort(arr, axis=None))

[21 14 13 23 20  8  0  6 16  4  7 18 11 10  5  3  9  2  1 22 24 12 15 19
 17]
