In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

### ```np.concatenate((a, b), axis=0)```

In [3]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [4]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ```np.vstack((a, b))``` 
### ```np.r_[a, b]```

In [5]:
# stack arrays vertically
cat = np.vstack((arr2, arr1))
print(cat)

[[5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]
 [1 2 3 4]]


In [6]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


### ```np.hstack((a, b))```
### ```np.c_[a, b]```

In [7]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [8]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### split an array 

In [9]:
arr = np.random.rand(6,6)

In [10]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1)

[array([[0.45403447, 0.23409939, 0.2372638 , 0.19720282, 0.18852157,
        0.85368456],
       [0.36810651, 0.68554491, 0.30161745, 0.84880213, 0.56991119,
        0.51626789],
       [0.71055552, 0.04562528, 0.72940666, 0.26621881, 0.04319455,
        0.22267284]]), array([[0.45266501, 0.27506345, 0.5555046 , 0.66400263, 0.0654979 ,
        0.78182516],
       [0.6305205 , 0.15288253, 0.11371323, 0.85222275, 0.83140857,
        0.73815018],
       [0.60573069, 0.44504818, 0.09308128, 0.69561447, 0.51307256,
        0.45361579]])]


In [11]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[0.45403447, 0.23409939, 0.2372638 ],
       [0.36810651, 0.68554491, 0.30161745],
       [0.71055552, 0.04562528, 0.72940666],
       [0.45266501, 0.27506345, 0.5555046 ],
       [0.6305205 , 0.15288253, 0.11371323],
       [0.60573069, 0.44504818, 0.09308128]]), array([[0.19720282, 0.18852157, 0.85368456],
       [0.84880213, 0.56991119, 0.51626789],
       [0.26621881, 0.04319455, 0.22267284],
       [0.66400263, 0.0654979 , 0.78182516],
       [0.85222275, 0.83140857, 0.73815018],
       [0.69561447, 0.51307256, 0.45361579]])]
